### ISSUE TITLE
Not exists config.php file

### ISSUE THREAD

**Issue by sorbing** [johnpaulhayes/Kindle-Highlights#2]
Warning: require_once(../configs/kindle_highlights_config.php): failed to open stream: No such file or directory in...

**Comment by johnpaulhayes** [comment]
Hi there,

You need to include a configuration file which holds your kindle username and password. If you look at the example.php script you'll see it included there.

I'll amend so as this is included but with dummy username and password.

## 

All the best,
John Paul.
