### ISSUE TITLE
You do not plan to add integration with tasks service?

### ISSUE THREAD

**Issue by sorbing** [johnpaulhayes/Kindle-Highlights#3]
For example export of highlights and notes to gtask. It would be very handy.

**Comment by johnpaulhayes** [comment]
Thanks for the suggestion. 
No plans for that as I've never heard of it before.
Perhaps you could contribute to the project with this integration?

**Comment by sorbing** [comment]
Yes, I want to to this if there is free time.
Very bad thing that the highlighting and notes does not support links. I already wrote about this to amazon support.
